### ISSUE TITLE
cannot install in magento 2.3

### ISSUE THREAD

**Issue by michhy** [Vendic/magento2-vuestorefront-xmlsitemap#12]
Hello there,
I tried to run composer require, but failed to install.
I am using magento 2.3
![螢幕截圖 2019-07-05 下午6 20 32](https://user-images.githubusercontent.com/37435427/60716369-ca7f0480-9f51-11e9-8ba0-bd4d2443dc39.png)

Thanks

**Comment by Tjitse-E** [comment]
Just tried this on a Magento 2.3.2 instance, and no problems there. If you do `composer show` you should see the `magento/magento2-base` package, which is required for this module.

**Comment by michhy** [comment]
Hi, my magento is working fine, but i cannot find the magento/magento2-base in compose.json.
I will try to download the package from here, upload and install by myself and try.

Thanks!

**Comment by Tjitse-E** [comment]
Try `composer show` it will give you a list of all the installed packages.

**Comment by michhy** [comment]
I found out from forums that, if I am not installing magento with composer, but git clone, it will not contain any magento2-base package. 

I tried install like custom modules, it will keep showing some error.
1/ I succeed to install the package and displaying correctly in magento (just putting it on server and run setup, without running composer update in advance.
2/ When I run bin/magento vsf:sitemap:generate, it will show 'cannot find sitemapPHP/sitemap '
3/ I tried to remove the two lines of magento package and run composer update (if I dont remove I cannot proceed), and try to install by bin/magento setup:upgrade again, it shows error: 
![螢幕截圖 2019-07-05 下午11 48 15](https://user-images.githubusercontent.com/37435427/60733424-62dfae00-9f7f-11e9-86e0-a0acfeb08816.png)

I am sorry but I cannot install magento by composer again (it is running and all data loaded for a while), not sure any other way to install the component.

Thanks in advance.

**Comment by michhy** [comment]
![螢幕截圖 2019-07-06 上午12 21 56](https://user-images.githubusercontent.com/37435427/60734905-177bce80-9f84-11e9-8708-5d3f12195892.png)

**Comment by Tjitse-E** [comment]
@michhy you are missing a dependency. Try running `composer require evert/sitemap-php:^1.2`

**Comment by michhy** [comment]
Thanks a lot! I succeeded.
